class Httpstates{
  //AARTI STATE
  static const String AARTIS="AARTI_INFO";
  static const String AARTI_INFO="AARTI_INFO";

  //AUTH STATE
  static const String CUSTOM_LOGIN="CUSTOM_LOGIN";
  static const String GOOGLE_LOGIN="GOOGLE_LOGIN";

  static const String TRY_AUTH="TRY_AUTH";
  static const String USER_INFO="USER_INFO";
  static const String REGISTER="REGISTER";
  static const String LOG_OUT="LOG_OUT";
  static const String FORGOT_PASSWORD="FORGOT_PASSWORD";
  static const String RESET_PASSWORD="RESET_PASSWORD";
  static const String UPDATE_PROFILE_META="UPDATE_PROFILE_META";
  static const String UPDATE_PASSWORD="UPDATE_PASSWORD";
  static const String DELETE_ME="DELETE_ME";
  static const String REVERIFY="REVERIFY";

  //BHAGVAD GEETA STATE
  static const String BHAGVAD_GEETA_CHAPTERS="REVERIFY";
  static const String BHAGVAD_GEETA_SHLOK_BY_CHAPTERID_SHLOKID="BHAGVAD_GEETA_SHLOK_BY_CHAPTERID_SHLOKID";
  static const String BHAGVAD_GEETA_SHLOK_BY_CHAPTERID_SHLOKNO="BHAGVAD_GEETA_SHLOK_BY_CHAPTERID_SHLOKNO";
  static const String BHAGVAD_GEETA_SHLOK_BY_CHAPTERNO_SHLOKNO="BHAGVAD_GEETA_SHLOK_BY_CHAPTERNO_SHLOKNO";
  static const String BHAGVAD_GEETA_SHLOKS="BHAGVAD_GEETA_SHLOKS";

  //BRAHMA SUTRA STATE
  static const String BRAHMA_SUTRA_INFO="BRAHMA_SUTRA_INFO";
  static const String BRAHMA_SUTRA_BY_SUTRAID="BRAHMA_SUTRA_BY_SUTRAID";
  static const String BRAHMA_SUTRA_BY_CHAPTERNO_QUATERNO_SUTRANO="BRAHMA_SUTRA_BY_CHAPTERNO_QUATERNO_SUTRANO";
  static const String BRAHMA_SUTRAS_BY_CHAPTERNO_QUATERNO="BRAHMA_SUTRAS_BY_CHAPTERNO_QUATERNO";

  //CHALISA STATE
  static const String ALL_CHALISA_INFO="ALL_CHALISA_INFO";
  static const String ALL_CHALISA="ALL_CHALISA";
  static const String CHALISA_BY_ID="CHALISA_BY_ID";
  static const String CHALISA_BY_TITLE="CHALISA_BY_TITLE";

  //CHANAKYA NEETI STATE
  static const String CHANAKYA_NEETI_CHAPTERS_INFO="CHANAKYA_NEETI_CHAPTERS_INFO";
  static const String CHANAKYA_NEETI_CHAPTER_VERSES="CHANAKYA_NEETI_CHAPTER_VERSES";
  static const String CHANAKYA_NEETI_VERSE_BY_CHAPTERNO_VERSENO="CHANAKYA_NEETI_VERSE_BY_CHAPTERNO_VERSENO";

  //MAHABHARAT STATE
  static const String MAHABHARATA_INFO="MAHABHARATA_INFO";
  static const String MAHABHARATA_SHLOK_BY_ID="MAHABHARATA_SHLOK_BY_ID";
  static const String MAHABHARATA_SHLOK_BY_SHLOKNO="MAHABHARATA_SHLOK_BY_SHLOKNO";
  static const String MAHABHARATA_SHLOKS_BY_BOOKNO_CHAPTERNO="MAHABHARATA_SHLOKS_BY_BOOKNO_CHAPTERNO";

  //MANTRA STATE
  static const String ALL_MANTRA_INFO="ALL_MANTRA_INFO";
  static const String ALL_MANTRA="ALL_MANTRA";
  static const String MANTRA_BY_ID="MANTRA_BY_ID";
  static const String MANTRA_AUDIO_BY_ID="MANTRA_BY_ID";
  static const String MANTRA_BY_TITLE="MANTRA_BY_TITLE";
  static const String MANTRA_AUDIO_BY_TITLE="MANTRA_BY_TITLE";

  //RAMAYANA STATE
  static const String RAMAYANA_INFO="RAMAYANA_INFO";
  static const String RAMAYANA_SARGA_INFO="RAMAYANA_SARGA_INFO";
  static const String RAMAYANA_SARGAS_INFO="RAMAYANA_SARGAS_INFO";
  static const String RAMAYANA_SHLOK_BY_KANDA_SARGANO_SHLOKNO="RAMAYANA_SHLOK_BY_KANDA_SARGANO_SHLOKNO";
  static const String RAMAYANA_SHLOK_BY_KAND_SARGAID_SHLOKNO="RAMAYANA_SHLOK_BY_KAND_SARGAID_SHLOKNO";
  static const String RAMAYANA_SHLOKAS_BY_KAND_SARGANO="RAMAYANA_SHLOKAS_BY_KAND_SARGANO";
  static const String RAMAYANA_SHLOKAS_BY_KAND_SARGAID="RAMAYANA_SHLOKAS_BY_KAND_SARGAID";

  //RAMCHARITMANAS STATE
  static const String RAMCHARITMANAS_INFO="RAMCHARITMANAS_INFO";
  static const String RAMCHARITMANAS_VERSE_BY_ID="RAMCHARITMANAS_VERSE_BY_ID";
  static const String RAMCHARITMANAS_VERSE_BY_KAND_VERSENO="RAMCHARITMANAS_VERSE_BY_KAND_VERSENO";
  static const String RAMCHARITMANAS_MANGALACHARAN_BY_KAND="RAMCHARITMANAS_MANGALACHARAN_BY_KAND";
  static const String RAMCHARITMANAS_ALL_MANGALACHARAN="RAMCHARITMANAS_ALL_MANGALACHARAN";
  static const String RAMCHARITMANAS_VERSES_BY_KAND="RAMCHARITMANAS_VERSES_BY_KAND";

  //RIGVEDA STATE
  static const String RIGVEDA_INFO="RIGVEDA_INFO";
  static const String RIGVEDA_VERSE_BY_MANDALA_SUKTA="RIGVEDA_VERSE_BY_MANDALA_SUKTA";
  static const String RIGVEDA_VERSE_BY_SUKTAID="RIGVEDA_VERSE_BY_SUKTAID";
  static const String RIGVEDA_VERSES_BY_MANDALA="RIGVEDA_VERSES_BY_MANDALA";

  //YOGA SUTRA STATE
  static const String YOGASUTRA_INFO="YOGASUTRA_INFO";
  static const String YOGASUTRA_BY_SUTRAID="YOGASUTRA_BY_SUTRAID";
  static const String YOGASUTRA_BY_CHAPTERNO_SUTRANO="YOGASUTRA_BY_CHAPTERNO_SUTRANO";
  static const String YOGASUTRAS_BY_CHAPTERNO="YOGASUTRAS_BY_CHAPTERNO";

  //GURU GRANTH SAHIB STATE
  static const String GURU_GRANTH_SAHIB_INFO="GURU_GRANTH_SAHIB_INFO";
  static const String GURU_GRANTH_SAHIB_RAGA="GURU_GRANTH_SAHIB_RAGA";

  //VRAT KATHA STATE
  static const String VRAT_KATHA="KATHA";
  static const String VRAT_KATHA_INFO_PAGE="KATHA_INFO_PAGE";
}